project_root: "${PROJECT_ROOT:-.}"
dataset_name: "dgl"

train_ratio: 0.60
val_ratio_to_train: 0.1
seed: 42
reverse_negative_count: 0
hard_negative_count: 0
label_file_negative_ratio_to_train: 1.5
label_file_negative_count: null

